#############################################################################
# Makefile for building: Interface
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  Interface.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Interface.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Interface1.0.0
DISTDIR = /media/vitorsorpile/LinuxExtraSpace/prog3/ControleDeLead/ETECH-LeadControl/Interface\ (copy)/.tmp/Interface1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib/x86_64-linux-gnu -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Empresa.cpp \
		src/Lead.cpp \
		src/create_empresa.cpp \
		src/create_lead.cpp \
		src/main.cpp \
		src/menu.cpp \
		src/App.cpp \
		src/table.cpp moc_create_empresa.cpp \
		moc_create_lead.cpp \
		moc_menu.cpp
OBJECTS       = Empresa.o \
		Lead.o \
		create_empresa.o \
		create_lead.o \
		main.o \
		menu.o \
		App.o \
		table.o \
		moc_create_empresa.o \
		moc_create_lead.o \
		moc_menu.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Interface.pro src/Empresa.h \
		src/Lead.h \
		src/create_empresa.h \
		src/create_lead.h \
		src/menu.h \
		src/App.h \
		src/table.h src/Empresa.cpp \
		src/Lead.cpp \
		src/create_empresa.cpp \
		src/create_lead.cpp \
		src/main.cpp \
		src/menu.cpp \
		src/App.cpp \
		src/table.cpp
QMAKE_TARGET  = Interface
DESTDIR       = 
TARGET        = Interface


first: all
####### Build rules

$(TARGET): ui_create_empresa.h ui_create_lead.h ui_menu.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Interface.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Interface.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Interface.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Interface.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Interface.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Empresa.h src/Lead.h src/create_empresa.h src/create_lead.h src/menu.h src/App.h src/table.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Empresa.cpp src/Lead.cpp src/create_empresa.cpp src/create_lead.cpp src/main.cpp src/menu.cpp src/App.cpp src/table.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/create_empresa.ui src/create_lead.ui src/menu.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_create_empresa.cpp moc_create_lead.cpp moc_menu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_create_empresa.cpp moc_create_lead.cpp moc_menu.cpp
moc_create_empresa.cpp: src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		src/create_empresa.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/media/vitorsorpile/LinuxExtraSpace/prog3/ControleDeLead/ETECH-LeadControl/Interface (copy)' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++ -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32 -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed -IE:/Qt-Windowns/Tools/mingw810_64/x86_64-w64-mingw32/include src/create_empresa.h -o moc_create_empresa.cpp

moc_create_lead.cpp: src/Lead.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		src/create_lead.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/media/vitorsorpile/LinuxExtraSpace/prog3/ControleDeLead/ETECH-LeadControl/Interface (copy)' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++ -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32 -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed -IE:/Qt-Windowns/Tools/mingw810_64/x86_64-w64-mingw32/include src/create_lead.h -o moc_create_lead.cpp

moc_menu.cpp: /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		src/table.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QTableWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtableview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyle.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabbar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qrubberband.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h \
		src/Lead.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QListWidgetItem \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistview.h \
		src/create_lead.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		src/create_empresa.h \
		src/App.h \
		src/menu.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/media/vitorsorpile/LinuxExtraSpace/prog3/ControleDeLead/ETECH-LeadControl/Interface (copy)' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++ -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32 -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include -IE:/Qt-Windowns/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed -IE:/Qt-Windowns/Tools/mingw810_64/x86_64-w64-mingw32/include src/menu.h -o moc_menu.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_create_empresa.h ui_create_lead.h ui_menu.h
compiler_uic_clean:
	-$(DEL_FILE) ui_create_empresa.h ui_create_lead.h ui_menu.h
ui_create_empresa.h: src/create_empresa.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/create_empresa.ui -o ui_create_empresa.h

ui_create_lead.h: src/create_lead.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/create_lead.ui -o ui_create_lead.h

ui_menu.h: src/menu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/menu.ui -o ui_menu.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Empresa.o: src/Empresa.cpp src/Empresa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Empresa.o src/Empresa.cpp

Lead.o: src/Lead.cpp src/Lead.h \
		src/Empresa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Lead.o src/Lead.cpp

create_empresa.o: src/create_empresa.cpp src/create_empresa.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		ui_create_empresa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o create_empresa.o src/create_empresa.cpp

create_lead.o: src/create_lead.cpp src/create_lead.h \
		src/Lead.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		ui_create_lead.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o create_lead.o src/create_lead.cpp

main.o: src/main.cpp src/menu.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		src/table.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QTableWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtableview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyle.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabbar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qrubberband.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h \
		src/Lead.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QListWidgetItem \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistview.h \
		src/create_lead.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		src/create_empresa.h \
		src/App.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

menu.o: src/menu.cpp src/menu.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		src/table.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QTableWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtableview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyle.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabbar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qrubberband.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h \
		src/Lead.h \
		src/Empresa.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QListWidgetItem \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistview.h \
		src/create_lead.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		src/create_empresa.h \
		src/App.h \
		ui_menu.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QFile \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QTextStream \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QPixmap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o src/menu.cpp

App.o: src/App.cpp src/App.h \
		src/Lead.h \
		src/Empresa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o App.o src/App.cpp

table.o: src/table.cpp src/table.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QTableWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtableview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyle.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabbar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qrubberband.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h \
		src/Lead.h \
		src/Empresa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o src/table.cpp

moc_create_empresa.o: moc_create_empresa.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_create_empresa.o moc_create_empresa.cpp

moc_create_lead.o: moc_create_lead.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_create_lead.o moc_create_lead.cpp

moc_menu.o: moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o moc_menu.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Interface/bin || mkdir -p $(INSTALL_ROOT)/opt/Interface/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Interface/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Interface/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Interface/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Interface/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

